### ISSUE TITLE
[Bug]: Unable to load image url with Backend::IMAGICK

### ISSUE THREAD

**Issue by Lukasss93** [sergix44/imagezen#11]
### What happened?

I got this error:

SergiX44\ImageZen\Exceptions\CannotLoadImageException
Cannot load an image from the specified path.

### How to reproduce the bug

$image = Image::make('any valid image url', Backend::IMAGICK);

### Package Version

latest

### PHP Version

8.3

### Which operating systems does with happen with?

Linux

**Comment by sergix44** [comment]
Fixed
